# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(852, 522)
        self.pictureLabel = QtWidgets.QLabel(Form)
        self.pictureLabel.setGeometry(QtCore.QRect(20, 10, 491, 491))
        self.pictureLabel.setText("")
        self.pictureLabel.setObjectName("pictureLabel")
        self.x_text = QtWidgets.QTextEdit(Form)
        self.x_text.setGeometry(QtCore.QRect(560, 60, 281, 31))
        self.x_text.setObjectName("x_text")
        self.show = QtWidgets.QPushButton(Form)
        self.show.setGeometry(QtCore.QRect(560, 440, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show.setFont(font)
        self.show.setObjectName("show")
        self.y_text = QtWidgets.QTextEdit(Form)
        self.y_text.setGeometry(QtCore.QRect(560, 140, 281, 31))
        self.y_text.setObjectName("y_text")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(560, 220, 281, 31))
        self.textEdit_3.setObjectName("textEdit_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.show.setText(_translate("Form", "Отобразить"))
